# Generated by Django 4.1.4 on 2022-12-23 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_entry_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
