# Generated by Django 4.1.4 on 2022-12-23 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_entry_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
