# Generated by Django 4.1.4 on 2022-12-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0007_alter_entry_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/'),
        ),
    ]
